# Generated by Django 6.0.2 on 2026-03-04 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_academicyear_alter_studentclass_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='child',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='child',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users_app.studentclass'),
        ),
    ]
