# Generated by Django 5.2.11 on 2026-03-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_date_activity_time_alter_activity_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
