# Generated by Django 5.2.11 on 2026-03-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
